
env = Environment( CC = 'g++',
                   LIBS    = ['boost_thread-mt', 'boost_system-mt'],
                   CCFLAGS = '-g -Wall -O0 -std=c++11',
                   LIBPATH = ['/usr/local/lib'],
                   CPPPATH = ['/user/local/include/boost'] )

env.Program( 'thread1.cpp' );
env.Program( 'scoped_thread1.cpp' );
